feat: add GitHub Actions pipeline

diff --git a/.github/workflows/main-pipeline.yml b/.github/workflows/main-pipeline.yml
--- a/.github/workflows/main-pipeline.yml
+++ b/.github/workflows/main-pipeline.yml
@@ -9,7 +9,21 @@ jobs:
     runs-on: self-hosted
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set working directory
+        run: |
+          echo "Working dir before:" $(pwd)
+          cd iot-turbine-project
+          echo "Working dir after cd:" $(pwd)
+        working-directory: ${{ github.workspace }}
+
+      - name: Debug Logs Directory
+        run: |
+          echo "📂 Current Directory:"; pwd
+          echo "📄 Files in current directory:"; ls -la
+          echo "📁 Files inside logs/ directory:"; ls -la logs/ || echo "⚠️ logs/ folder not found"
 
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -17,14 +31,9 @@ jobs:
           python-version: '3.10'
 
       - name: Install dependencies
-        run: |
-          pip install -r requirements.txt
+        run: pip install -r requirements.txt
 
       - name: Run Notebook 1 (AutoEDA)
         run: |
           pip install papermill
           papermill notebooks/notebook1_autoeda_cleaning.ipynb notebooks/output_autoeda.ipynb
-
-      - name: Run Notebook 2 (AutoML)
-        run: |
-          papermill notebooks/notebook2_automl.ipynb notebooks/output_automl.ipynb
